import react,{Component} from "react";

const anime = [
{"anime": "Tenet", "image": "https://upload.wikimedia.org/wikipedia/en/1/14/Tenet_movie_poster.jpg", "descreption": "<div><h5 class='theme-font'>Tenet</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>2020</li><li><div class='ttRating'>7.7</div></li></ul><p>The plot follows a secret agent (Washington) as he manipulates the flow of time to prevent World War III</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>Thriller</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Avengers: Endgame", "image": "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg", "descreption": "<div><h5 class='theme-font'>Avengers: Endgame</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>2019</li><li><div class='ttRating'>8.4</div></li></ul><p>The surviving members of the Avengers and their allies attempt to reverse the damage caused by Thanos in Infinity War</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>SuperHero</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Avatar", "image": "https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg", "descreption": "<div><h5 class='theme-font'>Avatar</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>2009</li><li><div class='ttRating'>8.3</div></li></ul><p>The film is set in the mid-22nd century when humans are colonizing Pandora in order to mine rare minerals</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>fantasy</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Titanic", "image": "https://upload.wikimedia.org/wikipedia/en/1/19/Titanic_%28Official_Film_Poster%29.png", "descreption": "<div><h5 class='theme-font'>Titanic</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>1997</li><li><div class='ttRating'>8.0</div></li></ul><p>The movie is based on accounts of the sinking of the RMS Titanic on its maiden voyage</p><div class='tags'><h4>Genre</h4><ul><li>Romance</li><li>Disaster</li></ul></div></div>"},
{"anime": "Star Wars: The Force Awakens", "image": "https://upload.wikimedia.org/wikipedia/en/a/a2/Star_Wars_The_Force_Awakens_Theatrical_Poster.jpg", "descreption": "<div><h5 class='theme-font'>Star Wars: The Force Awakens</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>2015</li><li><div class='ttRating'>8.3</div></li></ul><p>Set thirty years after Return of the Jedi, The Force Awakens follows Rey, Finn, Poe Dameron, and Han Solo's search for Luke Skywalker and their fight in the Resistance</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>Adventure</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Avengers: Infinity War", "image": "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg", "descreption": "<div><h5 class='theme-font'>Avengers: Infinity War</h5><ul class='entryBar'><li class='type'>Movie</li><li class='iconYear'>2018</li><li><div class='ttRating'>8.5</div></li></ul><p>The Avengers and the Guardians of the Galaxy attempt to prevent Thanos from collecting the six all-powerful Infinity Stones as part of his quest to kill half of all life in the universe</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>Adventure</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Seinfeld", "image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSlFnjtjjnAHQk0DFHyDCaJuVCDLztJNR2mEJiQJ249dnKRSzoQ", "descreption": "<div><h5 class='theme-font'>Seinfeld</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>1989-1998</li><li><div class='ttRating'>8.8</div></li></ul><p>Seinfeld is an American sitcom television series created by Larry David and Jerry Seinfeld</p><div class='tags'><h4>Genre</h4><ul><li>Sitcom</li></ul></div></div>"},
{"anime": "The Sopranos", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHOvOq-Ogk4oz6d49RxNbnYRSYug2T8gJ-rcTjokrjoLwtFYtR", "descreption": "<div><h5 class='theme-font'>The Sopranos</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>1999-2007</li><li><div class='ttRating'>9.2</div></li></ul><p>The Sopranos is an American crime drama television series created by David Chase</p><div class='tags'><h4>Genre</h4><ul><li>Crime</li><li>Drama</li></ul></div></div>"},
{"anime": "Breaking Bad", "image": "https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY268_CR5,0,182,268_AL__QL50.jpg", "descreption": "<div><h5 class='theme-font'>Breaking Bad</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>2008-2013</li><li><div class='ttRating'>9.5</div></li></ul><p>Breaking Bad is an American neo-Western crime drama television series created and produced by Vince Gilligan</p><div class='tags'><h4>Genre</h4><ul><li>Crime</li><li>Drama</li><li>Thriller</li></ul></div></div>"},
{"anime": "Lost", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk8v0j0ARPS6x6_3cZsFJ4Fr_QZqzxQf1v2Fp-CX3qNawP9aS4", "descreption": "<div><h5 class='theme-font'>Lost</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>2004-2010</li><li><div class='ttRating'>8.3</div></li></ul><p>The survivors of a plane crash find themselves stranded on a mysterious island</p><div class='tags'><h4>Genre</h4><ul><li>Adventure</li><li>Thriller</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Friends", "image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSHW7M_Pw-BVdUw5Mkw6imk1dteP1z0bQY73g9DJkfU-M-WM4Nq", "descreption": "<div><h5 class='theme-font'>Friends</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>1994-2004</li><li><div class='ttRating'>8.9</div></li></ul><p>Follow the lives of six reckless adults living in Manhattan, as they indulge in adventures which make their lives both troublesome and happening</p><div class='tags'><h4>Genre</h4><ul><li>Sitcom</li></ul></div></div>"},
{"anime": "The Simpsons", "image": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS0vGva0XuflbT97AOB8ra7FYyNMy4lOSoNnaiotzqQ8n4YvZgr", "descreption": "<div><h5 class='theme-font'>The Simpsons</h5><ul class='entryBar'><li class='type'>Tv Show</li><li class='iconYear'>1989-Present</li><li><div class='ttRating'>8.7</div></li></ul><p>Working-class father Homer Simpson and his dysfunctional family deal with comical situations and the ups-and-downs of life in the town of Springfield</p><div class='tags'><h4>Genre</h4><ul><li>Animated</li><li>Sitcom</li></ul></div></div>"},
{"anime": "Life goes on", "image": "https://upload.wikimedia.org/wikipedia/en/7/76/BTS_-_Life_Goes_On_%28Vinyl%29.png", "artist": "BTS", "descreption": "<div><h5 class='theme-font'>Life goes on</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Synth Pop</li><li>K-Pop</li></ul></div></div>"},
{"anime": "Mood", "image": "https://upload.wikimedia.org/wikipedia/en/1/1d/24kGoldn_-_Mood.png", "artist": "24kGoldn Featuring iann dior", "descreption": "<div><h5 class='theme-font'>Mood</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Pop</li><li>Hip Hop</li></ul></div></div>"},
{"anime": "Dynamite", "image": "https://upload.wikimedia.org/wikipedia/en/5/5f/BTS_-_Dynamite_%28official_cover%29.png", "artist": "BTS", "descreption": "<div><h5 class='theme-font'>Dynamite</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Disco</li><li>Pop</li></ul></div></div>"},
{"anime": "Positions", "image": "https://upload.wikimedia.org/wikipedia/en/b/bc/Positions_%28single%29.png", "artist": "Ariana Grande", "descreption": "<div><h5 class='theme-font'>Positions</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Pop</li><li>R&B</li></ul></div></div>"},
{"anime": "I Hope", "image": "https://upload.wikimedia.org/wikipedia/en/6/6f/Gabby_Barrett_-_I_Hope.png", "artist": "Gabby Barret feat. Charlie Puth", "descreption": "<div><h5 class='theme-font'>I Hope</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Pop</li><li>Country</li></ul></div></div>"},
{"anime": "Holy", "image": "https://upload.wikimedia.org/wikipedia/en/8/8d/Holy_-_Justin_Bieber.png", "artist": "Justin Beiber feat. Chance the rapper", "descreption": "<div><h5 class='theme-font'>Holy</h5><ul class='entryBar'><li class='type'>Song</li><li class='iconYear'>2020</li></ul><div class='tags'><h4>Genre</h4><ul><li>Pop</li><li>gospel</li></ul></div></div>"},
{"anime": "The Crown", "image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSgKfyJMqrJ7SWFGiJ8PZvGbRQnyWlTL7PLPiw58h83tm2WfPIJ", "descreption": "<div><h5 class='theme-font'>The Crown</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2016-Ongoing</li><li><div class='ttRating'>8.7</div></li></ul><p>Based on an award-winning play by showrunner Peter Morgan, this lavish, Netflix-original drama chronicles the life of Queen Elizabeth II from the 1940s to modern times</p><div class='tags'><h4>Genre</h4><ul><li>Historical</li><li>Drama</li></ul></div></div>"},
{"anime": "The Queen's Gambit", "image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQRfgOjyRzuClxEz8F5mkoGNHkoUvhLzfIS_ebXT6NIy_MqCLsL", "descreption": "<div><h5 class='theme-font'>The Queen's Gambit</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2020</li><li><div class='ttRating'>8.7</div></li></ul><p>Set during the Cold War era, orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest chess player in the world</p><div class='tags'><h4>Genre</h4><ul><li>Coming-of-age</li><li>Period Drama</li></ul></div></div>"},
{"anime": "The Umbrella Academy", "image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTGmLFCbr45HyfANTQHdeayH8zeVsozrKiScdROp5OuhstmENRe", "descreption": "<div><h5 class='theme-font'>The Umbrella Academy</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2019-Ongoing</li><li><div class='ttRating'>8.0</div></li></ul><p>The Umbrella Academy is an American superhero streaming television series based on the comic book series of the same name written by Gerard Way</p><div class='tags'><h4>Genre</h4><ul><li>Sci-fi</li><li>Action</li></ul></div></div>"},
{"anime": "The Boys", "image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQLu7zv8jPbv0SxipKFmCy9d-wkxtXX1XX5WrDhlc-qYRTjgDtK", "descreption": "<div><h5 class='theme-font'>The Boys</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2019-Ongoing</li><li><div class='ttRating'>8.7</div></li></ul><p>Based on the comic book of the same name by Garth Ennis and Darick Robertson, it follows the eponymous team of vigilantes as they combat superpowered individuals who abuse their abilities</p><div class='tags'><h4>Genre</h4><ul><li>Action</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "The Mandalorian", "image": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSLYAr8ki6lKEaBXFOBvF05eb4aGZ6STS5808wh-wT27SuGxBen", "descreption": "<div><h5 class='theme-font'>The Mandalorian</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2019-Ongoing</li><li><div class='ttRating'>8.7</div></li></ul><p>A lone gunfighter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.</p><div class='tags'><h4>Genre</h4><ul><li>Adventure</li><li>Sci-fi</li></ul></div></div>"},
{"anime": "Westworld", "image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSye_JHp4TwnrHkl6SQIkoBRX5AvUfJbpBBadHufXzq9lpSOBxj", "descreption": "<div><h5 class='theme-font'>Westworld</h5><ul class='entryBar'><li class='type'>Web Series</li><li class='iconYear'>2016-Ongoing</li><li><div class='ttRating'>8.7</div></li></ul><p>In a futuristic Western-themed amusement park, Westworld, the visitors interact with automatons. However, all hell breaks loose when the robots begin malfunctioning.</p><div class='tags'><h4>Genre</h4><ul><li>Sci-fi</li><li>Drama</li></ul></div></div>"},
{"anime": "A Tale of Two Cities", "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Tales_serial.jpg", "author": "Charles Dickens", "descreption": "<div><h5 class='theme-font'>A Tale of Two Cities</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>1859</li></ul><p>The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris and his release to live in London with his daughter Lucie, whom he had never met</p><div class='tags'><h4>Genre</h4><ul><li>Historical</li><li>Fiction</li></ul></div></div>"},
{"anime": "Harry Potter and the Philosopher's Stone", "image": "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg", "author": "J.K. Rowling", "descreption": "<div><h5 class='theme-font'>Harry Potter and the Philosopher's Stone</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>1997</li></ul><p>The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry</p><div class='tags'><h4>Genre</h4><ul><li>Fantasy</li><li>Fiction</li></ul></div></div>"},
{"anime": "The Lion, the Witch and the Wardrobe", "image": "https://upload.wikimedia.org/wikipedia/en/8/86/TheLionWitchWardrobe%281stEd%29.jpg", "author": "C.S. Lewis", "descreption": "<div><h5 class='theme-font'>The Lion, the Witch and the Wardrobe</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>1950</li></ul><p>The novel is set in Narnia, a land of talking animals and mythical creatures that is ruled by the evil White Witch</p><div class='tags'><h4>Genre</h4><ul><li>Fantasy</li><li>Fiction</li></ul></div></div>"},
{"anime": "She: A History of Adventure", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/SHE%2C_A_History_of_Adventure_%281st_Edition_Cover%29%2C_by_H._Rider_Haggard.jpg/440px-SHE%2C_A_History_of_Adventure_%281st_Edition_Cover%29%2C_by_H._Rider_Haggard.jpg", "author": "H. Rider Haggard", "descreption": "<div><h5 class='theme-font'>She: A History of Adventure</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>1887</li></ul><p>The story is a first-person narrative which follows the journey of Horace Holly and his ward Leo Vincey to a lost kingdom in the African interior</p><div class='tags'><h4>Genre</h4><ul><li>Adventure</li><li>Romance</li></ul></div></div>"},
{"anime": "The Adventures of Pinocchio", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Pinocchio.jpg/380px-Pinocchio.jpg", "author": "Carlo Collodi", "descreption": "<div><h5 class='theme-font'>The Adventures of Pinocchio</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>1881</li></ul><p>It is about the mischievous adventures of an animated marionette named Pinocchio and his father, a poor woodcarver named Geppetto</p><div class='tags'><h4>Genre</h4><ul><li>Literature</li><li>Fiction</li></ul></div></div>"},
{"anime": "The Da Vinci Code", "image": "https://upload.wikimedia.org/wikipedia/en/6/6b/DaVinciCode.jpg", "author": "Dan Brown", "descreption": "<div><h5 class='theme-font'>The Da Vinci Code</h5><ul class='entryBar'><li class='type'>Book</li><li class='iconYear'>2003</li></ul><p>The Da Vinci Code follows symbologist Robert Langdon and cryptologist Sophie Neveu after a murder in the Louvre Museum in Paris causes them to become involved in a battle between the Priory of Sion and Opus Dei over the possibility of Jesus Christ and Mary Magdalene having had a child together</p><div class='tags'><h4>Genre</h4><ul><li>Mystery</li><li>Thriller</li></ul></div></div>"},
]


export default anime;